# Generated by Django 6.0.2 on 2026-02-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=200)),
                ('studentid', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('relationship_status', models.CharField(max_length=20)),
                ('year_level', models.CharField(max_length=20)),
            ],
        ),
    ]
