# Generated by Django 5.2.10 on 2026-02-15 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_studentname_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentName',
            new_name='Student',
        ),
    ]
