# Generated by Django 6.0.2 on 2026-02-21 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_course_yearlevel_remove_student_relationship_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='yearlevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.yearlevel'),
        ),
    ]
